# Generated by Django 3.2.9 on 2022-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='20220207_224533', max_length=100, unique=True)),
                ('size', models.FloatField(default=0)),
                ('duration', models.TimeField(default=0)),
                ('created', models.DateTimeField()),
                ('falling', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'video_info',
            },
        ),
    ]
