# Generated by Django 3.2.9 on 2022-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='duration',
            field=models.TimeField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='size',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='title',
            field=models.CharField(default='20220207_232330', max_length=100, unique=True),
        ),
    ]
