# Generated by Django 3.2.9 on 2022-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_info', '0003_alter_videoinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='title',
            field=models.CharField(default='20220207_235934', max_length=100, unique=True),
        ),
    ]
