# Generated by Django 3.2.9 on 2022-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_info', '0006_auto_20220208_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='file_path',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='title',
            field=models.CharField(default='20220208_153326', max_length=100, unique=True),
        ),
    ]
