# Generated by Django 3.2.9 on 2022-02-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_info', '0007_auto_20220208_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='title',
            field=models.CharField(default='20220208_191623', max_length=100, unique=True),
        ),
    ]
